/**
 * MDX plugin.
 *
 * Vite is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://www.npmjs.com/package/@mdx-js/rollup
 */

import pluginConfig from '@mdx-js/rollup';
import path from 'node:path';
import u from '../../../../../resources/utilities.mjs';

/**
 * Configures MDX plugin.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       MDX plugin.
 */
export default async (/* {} */) => {
    return pluginConfig(await config({}));
};

/**
 * Produces MDX plugin configuration.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       MDX plugin configuration.
 */
export const config = async (/* {} */) => ({
    exclude: [
        ...new Set([
            ...u.exclusions.localIgnores, //
            ...u.exclusions.logIgnores,
            ...u.exclusions.backupIgnores,
            ...u.exclusions.patchIgnores,
            ...u.exclusions.editorIgnores,
            ...u.exclusions.toolingIgnores,
            ...u.exclusions.pkgIgnores,
            ...u.exclusions.vcsIgnores,
            ...u.exclusions.osIgnores,
            ...u.exclusions.dotIgnores,
            ...u.exclusions.dtsIgnores,
            ...u.exclusions.configIgnores,
            ...u.exclusions.lockIgnores,
            ...u.exclusions.devIgnores,
            ...u.exclusions.distIgnores,
            ...u.exclusions.docIgnores,
        ]),
    ],
    include: [
        '**/*.' +
            u.extensions.asBracedGlob([
                ...u.extensions.byVSCodeLang.markdown, // Single default export only.
                ...u.extensions.byVSCodeLang.mdx, // Default + potentially other exports.
            ]),
    ],
    ...(await (await import(path.resolve(u.projDir, './mdx.config.mjs'))).default()),
});
