##
# Wrangler configuration.
#
# @note Wrangler is aware of this config file's location.
#
# @note CUSTOM EDITS ONLY PLEASE!
# In the future this file will be updated automatically.
# Only `<custom:start.../custom:end>` will be preserved below.
##
compatibility_date = "2022-08-04"
compatibility_flags = ["global_navigator"]

account_id = "f1176464a976947aa5665d989814a4b1"

main = "./dst/index.js"
vars = { IS_C10N = "cfw=prod" }
build = { command = "npm run build:prod" }

site = { bucket = "./dst/assets", exclude = [".#*", "._*", ".~*", "*.local", "*.log", "*~", "*.bak", "*.rej", "*.orig", "*.patch", "*.diff", "dist/", ".vagrant/", "typings/", ".tscache/", "*.tsbuildinfo", ".idea/", "*.sublime-project", "*.sublime-workspace", "*.nbproject", ".vscode/", "*.code-workspace", "npm-debug.log", ".yarn/", "vendor/", "node_modules/", "jspm_packages/", "bower_components/", ".vite/", ".wrangler/", ".linaria-cache/", ".sass-cache/", ".docker/", ".elasticbeanstalk/", "*.ctags", "*.tags", ".git/", ".git-dir/", ".svn/", "_svn/", "CVS/", ".cvsignore", ".bzr/", ".bzrignore", ".hg/", ".hgignore", "SCCS/", "RCS/", "$RECYCLE.BIN/", "Desktop.ini", "Thumbs.db", "ehthumbs.db", ".AppleDB", ".AppleDouble", ".AppleDesktop", ".com.apple.timemachine.donotpresent", "Network Trash Folder", "Temporary Items", ".LSOverride", ".Spotlight-V100", ".VolumeIcon.icns", ".TemporaryItems", ".fseventsd", ".DS_Store", ".Trashes", ".apdisk", "Icon?", "!Icons", "._*"] }

##
# Customizations
# <custom:start>

name = "clevercanyon.skeleton"
routes = ["clevercanyon.skeleton/*"]

# </custom:end>

[env.dev]
workers_dev = true
vars = { IS_C10N = "cfw=dev" }
