/**
 * Cssnano config file.
 *
 * @since 1.0.0
 *
 * @note CSSNano doesn't know where this file lives.
 * @see https://cssnano.co/docs/config-file/
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * This file will be updated automatically.
 * - Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */
/* eslint-env es2021, node */

export default async ( /* srcDir = '' */ ) => {
	return {
		preset : [ 'default', { discardComments : { removeAll : true } } ],
	};
};
