/**
 * PostCSS config file.
 *
 * @since 1.0.0
 *
 * @note PostCSS doesn't know where this file lives.
 * @see https://github.com/csstools/postcss-plugins/blob/main/plugin-packs/postcss-preset-env/FEATURES.md
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * This file will be updated automatically.
 * - Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */
/* eslint-env es2021, node */

import tailwind from './tailwind.js';
import cssnano  from './cssnano.js';

export default async ( srcDir = '' ) => {
	return {
		plugins : [
			[ 'postcss-import', {} ],
			[ 'tailwindcss', await tailwind( srcDir ) ],
			[ 'postcss-preset-env', { stage : 3 } ],
			[ 'cssnano', await cssnano( srcDir ) ],
		],
	};
};
