/**
 * Tailwind CSS config file.
 *
 * @since 1.0.0
 *
 * @note Tailwind doesn't know where this file lives.
 * @see https://tailwindcss.com/docs/configuration
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * This file will be updated automatically.
 * - Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */
/* eslint-env es2021, node */

/* @formatter:ignore
-----------------------------------------------------------------------------------------------------------------------
Example `index.scss` starter file contents:
-----------------------------------------------------------------------------------------------------------------------
@import 'https://fonts.googleapis.com/css2?family=Georama:ital,wght@0,100..900;1,100..900&display=swap';

@tailwind base;
@tailwind components;
@tailwind utilities;
------------------------------------------------------------------------------------------------- @formatter:/ignore */

import path from 'path';

export default async ( srcDir = '' ) => {
	return {
		theme   : {
			fontFamily : {
				sans  : [ 'Georama', 'sans-serif' ],
				serif : [ 'Georgia', 'serif' ],
			},
		},
		content : [
			path.resolve( srcDir, '*.{md,xml,html,shtml,php,js,cjs,mjs,jsx,ts,tsx}' ),
			path.resolve( srcDir, '**/*.{md,xml,html,shtml,php,js,cjs,mjs,jsx,ts,tsx}' ),
		],
	};
};
