/**
 * Tailwind CSS settings file.
 *
 * Tailwind is not aware of this config file's location. We use the exports provided by this file to centralize a few
 * settings associated with Tailwind that are reused across various tools that integrate with Tailwind CSS.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */

import path from 'node:path';
import { $fs } from '../../../node_modules/@clevercanyon/utilities.node/dist/index.js';

const __dirname = $fs.imuDirname(import.meta.url);
const projDir = path.resolve(__dirname, '../../..');

/**
 * Defines Tailwind settings.
 */
export default {
    classFunctions: ['$preact.classes'],
    classAttributesRegExpStr: '^class(?:es|Names?)?$',
    classAttributesRegExp: new RegExp('^class(?:es|Names?)?$', 'u'),
    classAttributes: ['class', 'classes', 'className', 'classNames'],
    configFile: path.resolve(projDir, './tailwind.config.mjs'),
};
