/**
 * Vite config file.
 *
 * @note Vite is not aware of this config file's location.
 * @see https://vitejs.dev/config/
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * This entire file will be updated automatically.
 * - Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */
/* eslint-env es2021, node */

import desm from 'desm';
import path from 'node:path';

const __dirname = desm( import.meta.url );
const projDir   = path.resolve( __dirname, '../../../..' );
const srcDir    = path.resolve( projDir, './src' );

export default [ // See also: `../typescript/config.json`.
	{
		find        : /^@\/~(.+)$/u,
		replacement : path.resolve( srcDir, './$1' ),
	},
	{
		find        : /^@\/c10n\/u$/u,
		replacement : path.resolve( srcDir, '../node_modules/@clevercanyon/utilities' ),
	},
	{
		find        : /^@\/c10n\/u\/(.+)$/u,
		replacement : path.resolve( srcDir, '../node_modules/@clevercanyon/utilities/$1' ),
	},
	{
		find        : /^@\/c10n\/(?!u$|u\/)(.+)$/u,
		replacement : path.resolve( srcDir, '../node_modules/@clevercanyon/$1' ),
	},
];
