/**
 * Vite config file.
 *
 * @note Vite is not aware of this config file's location.
 * @see https://vitejs.dev/config/
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * This entire file will be updated automatically.
 * - Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */
/* eslint-env es2021, node */

import desm from 'desm';
import path from 'path';

const __dirname = desm( import.meta.url );
const projDir   = path.resolve( __dirname, '../../../..' );

export default [ // See also: `../typescript/config.json`.
	{
		find        : /^@\/@clevercanyon\/utilities\/u\/(.+)$/u,
		replacement : path.resolve( projDir, './node_modules/@clevercanyon/utilities/src/envs/any' ) + '/$1',
	},
	{
		find        : /^@\/@clevercanyon\/utilities\/c\/(.+)$/u,
		replacement : path.resolve( projDir, './node_modules/@clevercanyon/utilities/src/envs/cfw' ) + '/$1',
	},
	{
		find        : /^@\/@clevercanyon\/utilities\/n\/(.+)$/u,
		replacement : path.resolve( projDir, './node_modules/@clevercanyon/utilities/src/envs/node' ) + '/$1',
	},
	{
		find        : /^@\/@clevercanyon\/utilities\/w\/(.+)$/u,
		replacement : path.resolve( projDir, './node_modules/@clevercanyon/utilities/src/envs/web' ) + '/$1',
	},
	{
		find        : /^@\/@clevercanyon\/utilities\/u:(.+)$/u,
		replacement : path.resolve( projDir, './node_modules/@clevercanyon/utilities/src/envs/any/classes' ) + '/$1',
	},
	{
		find        : /^@\/@clevercanyon\/utilities\/c:(.+)$/u,
		replacement : path.resolve( projDir, './node_modules/@clevercanyon/utilities/src/envs/cfw/classes' ) + '/$1',
	},
	{
		find        : /^@\/@clevercanyon\/utilities\/n:(.+)$/u,
		replacement : path.resolve( projDir, './node_modules/@clevercanyon/utilities/src/envs/node/classes' ) + '/$1',
	},
	{
		find        : /^@\/@clevercanyon\/utilities\/w:(.+)$/u,
		replacement : path.resolve( projDir, './node_modules/@clevercanyon/utilities/src/envs/web/classes' ) + '/$1',
	},
];
