/**
 * Vitest config file.
 *
 * Vitest is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://vitest.dev/config/
 */

import path from 'node:path';
import exclusions from '../../../bin/includes/exclusions.mjs';
import extensions from '../../../bin/includes/extensions.mjs';

/**
 * Configures tests for Vite.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       Vitest configuration.
 */
export default async ({ projDir, srcDir, logsDir, targetEnv, vitestSandboxEnable, vitestExamplesEnable, rollupConfig }) => {
	const vitestExcludes = [
		...exclusions.vcsFilesDirs,
		...exclusions.packageDirs,
		...exclusions.dotFilesDirs,
		...exclusions.dotConfigFilesDirs,
		...exclusions.dtsFiles,
		...exclusions.distDirs,
		...exclusions.devDirs,
		...exclusions.docDirs,
		...(vitestSandboxEnable ? [] : [...exclusions.sandboxDirs]),
		...(vitestExamplesEnable ? [] : [...exclusions.exampleDirs]),
		...exclusions.xDirs, // Deliberate ad-hoc exclusions.
	];
	const vitestWatchExcludes = [
		...exclusions.vcsFilesDirs,
		...exclusions.packageDirs,
		...exclusions.dotFilesDirs,
		...exclusions.dotConfigFilesDirs,
		...exclusions.dtsFiles,
		...exclusions.distDirs,
		...exclusions.devDirs,
		...exclusions.docDirs,
		...(vitestSandboxEnable ? [] : [...exclusions.sandboxDirs]),
		...(vitestExamplesEnable ? [] : [...exclusions.exampleDirs]),
		// ...exclusions.xDirs -- Excluded from tests, but we still watch these.
	];
	const vitestIncludes =
		vitestSandboxEnable || vitestExamplesEnable
			? [
					...(vitestSandboxEnable ? ['**/{sandbox,__sandbox__}/**/*.{test,tests,spec,specs}.' + extensions.asGlob(extensions.jts)] : []),
					...(vitestExamplesEnable ? ['**/{example,examples,__example__,__examples__}/**/*.{test,tests,spec,specs}.' + extensions.asGlob(extensions.jts)] : []),
			  ]
			: [
					'**/*.{test,tests,spec,specs}.' + extensions.asGlob(extensions.jts),
					'**/{test,tests,spec,specs,__test__,__tests__,__spec__,__specs__}/**/*.' + extensions.asGlob(extensions.jts),
			  ];
	const vitestTypecheckIncludes =
		vitestSandboxEnable || vitestExamplesEnable
			? [
					...(vitestSandboxEnable ? ['**/{sandbox,__sandbox__}/**/*.{test,tests,spec,specs}-d.' + extensions.asGlob(extensions.ts)] : []),
					...(vitestExamplesEnable ? ['**/{example,examples,__example__,__examples__}/**/*.{test,tests,spec,specs}-d.' + extensions.asGlob(extensions.ts)] : []),
			  ]
			: [
					'**/*.{test,tests,spec,specs}-d.' + extensions.asGlob(extensions.ts),
					'**/{test,tests,spec,specs,__test__,__tests__,__spec__,__specs__}/**/*-d.' + extensions.asGlob(extensions.ts),
			  ];
	const vitestBenchIncludes =
		vitestSandboxEnable || vitestExamplesEnable
			? [
					...(vitestSandboxEnable ? ['**/{sandbox,__sandbox__}/**/*.{bench,benchmark,benchmarks}.' + extensions.asGlob(extensions.jts)] : []),
					...(vitestExamplesEnable ? ['**/{example,examples,__example__,__examples__}/**/*.{bench,benchmark,benchmarks}.' + extensions.asGlob(extensions.jts)] : []),
			  ]
			: [
					'**/*.{bench,benchmark,benchmarks}.' + extensions.asGlob(extensions.jts),
					'**/{bench,benchmark,benchmarks,__bench__,__benchmark__,__benchmarks__}/**/*.' + extensions.asGlob(extensions.jts),
			  ];
	return {
		root: srcDir,

		include: vitestIncludes,
		css: { include: /.+/u },

		exclude: vitestExcludes,
		watchExclude: vitestWatchExcludes,

		restoreMocks: true, // Remove all mocks before a test begins.
		unstubEnvs: true, // Remove all env stubs before a test begins.
		unstubGlobals: true, // Remove all global stubs before a test begins.

		environment: ['cfp', 'web'].includes(targetEnv) ? 'jsdom' // <https://o5p.me/Gf9Cy5>.
			: ['cfw', 'webw'].includes(targetEnv) ? 'miniflare' // <https://o5p.me/TyF9Ot>.
			: ['node', 'any'].includes(targetEnv) ? 'node' // <https://o5p.me/Gf9Cy5>.
			: /* fallback */ 'node', // prettier-ignore

		// See: <https://o5p.me/8Pjw1d> for `environment`, `environmentMatchGlobs` precedence.
		environmentMatchGlobs: [
			['**/*.{cfp,web}.{test,tests,spec,specs}.' + extensions.asGlob(extensions.jts), 'jsdom'],
			['**/{test,tests,spec,specs,__test__,__tests__,__spec__,__specs__}/**/*.{cfp,web}.' + extensions.asGlob(extensions.jts), 'jsdom'],

			['**/*.{cfw,webw}.{test,tests,spec,specs}.' + extensions.asGlob(extensions.jts), 'miniflare'],
			['**/{test,tests,spec,specs,__test__,__tests__,__spec__,__specs__}/**/*.{cfw,webw}.' + extensions.asGlob(extensions.jts), 'miniflare'],

			['**/*.{node,any}.{test,tests,spec,specs}.' + extensions.asGlob(extensions.jts), 'node'],
			['**/{test,tests,spec,specs,__test__,__tests__,__spec__,__specs__}/**/*.{node,any}.' + extensions.asGlob(extensions.jts), 'node'],
		],
		server: { deps: { external: [...new Set([...exclusions.packageDirs].concat(rollupConfig.external))] } },
		cache: { dir: path.resolve(projDir, './node_modules/.vitest') },

		passWithNoTests: true, // Pass if there are no tests to run.
		allowOnly: true, // Allows `describe.only`, `test.only`, `bench.only`.

		watch: false, // Disable watching by default.
		forceRerunTriggers: [...exclusions.devDirs, ...exclusions.dotConfigFilesDirs],

		reporters: ['verbose'], // Verbose reporting.
		// {@see https://o5p.me/p0f9j5} for further details.

		outputFile: {
			json: path.resolve(logsDir, './tests/vitest.json'),
			junit: path.resolve(logsDir, './tests/vitest.junit'),
			html: path.resolve(logsDir, './tests/vitest/index.html'),
		},
		typecheck: {
			include: vitestTypecheckIncludes,
			exclude: vitestExcludes,
		},
		coverage: {
			all: true,
			extension: [...extensions.jts],
			include: ['**/*.' + extensions.asGlob([...extensions.jts])],
			exclude: [...new Set([...vitestExcludes, ...vitestIncludes, ...vitestTypecheckIncludes, ...vitestBenchIncludes])],
			reporter: ['text', 'html', 'clover', 'json'], // Produces all report formats.
			reportsDirectory: path.resolve(logsDir, './coverage/vitest'),
		},
		benchmark: {
			include: vitestBenchIncludes,
			includeSource: vitestIncludes,
			exclude: vitestExcludes,

			outputFile: {
				json: path.resolve(logsDir, './benchmarks/vitest.json'),
				junit: path.resolve(logsDir, './benchmarks/vitest.junit'),
				html: path.resolve(logsDir, './benchmarks/vitest.html'),
			},
		},
	};
};
