/**
 * Prefresh plugin.
 *
 * Vite is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://www.npmjs.com/package/@prefresh/vite
 */

import pluginConfig from '@prefresh/vite';
import u from '../../../../../resources/utilities.mjs';

/**
 * Configures prefresh plugin.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       Prefresh plugin.
 */
export default async () => {
    return pluginConfig({
        exclude: [
            ...new Set([
                ...u.exclusions.localIgnores, //
                ...u.exclusions.logIgnores,
                ...u.exclusions.backupIgnores,
                ...u.exclusions.patchIgnores,
                ...u.exclusions.editorIgnores,
                ...u.exclusions.toolingIgnores,
                ...u.exclusions.pkgIgnores,
                ...u.exclusions.vcsIgnores,
                ...u.exclusions.osIgnores,
                ...u.exclusions.dotIgnores,
                ...u.exclusions.dtsIgnores,
                ...u.exclusions.configIgnores,
                ...u.exclusions.lockIgnores,
                ...u.exclusions.devIgnores,
                ...u.exclusions.distIgnores,
                ...u.exclusions.docIgnores,
            ]),
        ],
        include: [
            '**/*.' +
                u.extensions.asBracedGlob([
                    ...u.extensions.byDevGroup.allJavaScriptReact, //
                    ...u.extensions.byDevGroup.allTypeScriptReact,
                ]),
        ],
    });
};
