/**
 * Remark plugin.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */

import { h } from 'hastscript';
import { visit as unistVisit } from 'unist-util-visit';

/**
 * Generates alerts from a remark directive.
 */
export default () => {
    return (tree) => {
        unistVisit(tree, (node) => {
            if ('containerDirective' === node.type) {
                if (node.name !== 'alert') return;

                const data = node.data || (node.data = {});
                const atts = node.attributes || (node.attributes = {});
                const props = { className: '', 'aria-label': 'Alert' };

                props.className += ' bg-color-' + (atts.color || 'neutral');
                props.className += ' text-color-' + (atts.color || 'neutral') + '-fg';
                props.className += ' border-color-' + (atts.color || 'neutral') + '-bdr';
                if (atts.size) {
                    props.className += ' text-' + atts.size; // w/ auto-relative downsizing.
                    if ('xs' !== atts.size) props.className += ' lte-laptop:[&_>*]:text-smaller';
                }
                props.className += ' rounded border my-p p-4';
                props.className += ' [&_>*]:my-0'; // No margin on immediate children.
                props.className = props.className.trim();

                data.hName = 'div'; // Block-level container.
                data.hProperties = h(data.hName, props).properties;
            }
        });
    };
};
