/**
 * Remark plugin.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */

import { h } from 'hastscript';
import { visit as unistVisit } from 'unist-util-visit';

/**
 * Generates a table of contents, when applicable, and exports it.
 */
export default () => {
    return (tree) => {
        unistVisit(tree, (node) => {
            if ('containerDirective' === node.type) {
                if (node.name !== 'alert') return;
                const data = node.data || (node.data = {});
                const atts = node.attributes || (node.attributes = {});

                const props = {}; // Initialize.
                props['aria-label'] = 'Alert';

                props.className = ''; // Initialize.
                props.className += ' bg-color-' + (atts.color || 'neutral');
                props.className += ' text-color-' + (atts.color || 'neutral') + '-fg';
                props.className += ' border-color-' + (atts.color || 'neutral') + '-bdr';
                props.className += ' rounded border';
                props.className += ' p-4';
                props.className += ' [&_>*]:my-0';

                data.hName = 'p';
                data.hProperties = h(data.hName, props).properties;
            }
        });
    };
};
