/**
 * Remark config file.
 *
 * Remark is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 *
 * @see https://github.com/remarkjs/remark/tree/main/packages/remark-stringify#options
 */

import pluginDirective from 'remark-directive';
import pluginFrontmatter from 'remark-frontmatter';
import pluginGFM from 'remark-gfm';
import remarkLint from 'remark-lint';
import pluginMermaid from 'remark-mermaidjs';
import presetLintRecommended from 'remark-preset-lint-recommended';
import presetPrettier from 'remark-preset-prettier';
import pluginSmartyPants from 'remark-smartypants';

/**
 * Defines Remark configuration.
 */
export default async () => {
    /**
     * Composition.
     */
    return {
        settings: {
            // Headings.
            setext: false,
            closeAtx: false,

            // Strong, emphasis.
            // Mostly irrelevant since we are using the GFM plugin.
            strong: '*', // GFM enables support for `**bold**` or `__italic__`.
            emphasis: '_', // GFM enables support for `*italic*` or `_italic_`.

            // List items.
            bullet: '-',
            bulletOther: '*',
            bulletOrdered: '.',
            incrementListMarker: true,
            listItemIndent: 'mixed',

            // Fenced code blocks.
            fence: '`',
            fences: false,

            // Horizontal rules.
            rule: '-',
            ruleSpaces: true,
            ruleRepetition: 3,

            // Misc settings.
            quote: '"', // Quote to use around titles.
            resourceLink: false, // Always use resource links?
            tightDefinitions: false, // Join definitions w/o a blank line?
        },
        plugins: [
            remarkLint, // Remark core linter.
            presetLintRecommended, // Linting basics.
            presetPrettier, // Removes conflicting lint rules.

            pluginFrontmatter, // Frontmatter.
            [pluginGFM, { singleTilde: false }], // GFM features.
            pluginSmartyPants, // (em dash) `--` to `—`, quotes, etc.
            pluginMermaid, // Charting and diagramming; {@see https://o5p.me/5z7Yrt}.
            pluginDirective, // Custom directives; {@see https://o5p.me/0fakce}.

            // Disable this rule, as GFM explicitly allows this.
            ['remark-lint-no-literal-urls', false],
        ],
    };
};
