#!/usr/bin/env node
/**
 * Mad Run CLI config.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */
/* eslint-env es2021, node */

import events from './includes/events.mjs';

export default {
	'envs': './dev/.files/bin/envs.mjs {{@}}',
	'envs:install': './dev/.files/bin/envs.mjs install {{@}}',

	'envs:push': './dev/.files/bin/envs.mjs push {{@}}',
	'envs:pull': './dev/.files/bin/envs.mjs pull {{@}}',
	'envs:compile': './dev/.files/bin/envs.mjs compile {{@}}',

	'envs:keys': './dev/.files/bin/envs.mjs keys {{@}}',
	'envs:encrypt': './dev/.files/bin/envs.mjs encrypt {{@}}',
	'envs:decrypt': './dev/.files/bin/envs.mjs decrypt {{@}}',

	'dev': async (args) => 'npx vite dev' + (args.mode ? '' : ' --mode=dev') + ' {{@}}',
	'preview': async (args) => 'npx vite preview' + (args.mode ? '' : ' --mode=dev') + ' {{@}}',
	'build': async (args) => 'npx vite build' + (args.mode ? '' : ' --mode=prod') + ' {{@}}',

	'install': './dev/.files/bin/install.mjs {{@}}',
	'install:project': './dev/.files/bin/install.mjs project {{@}}',

	'update': './dev/.files/bin/update.mjs {{@}}',
	'update:dotfiles': './dev/.files/bin/update.mjs dotfiles {{@}}',
	'update:project': async (args) => [
		...(args.help || args.version ? [] : ['./dev/.files/bin/update.mjs dotfiles {{--dryRun}}']),
		'./dev/.files/bin/update.mjs project {{@}}', // prettier-ignore
	],
	'update:projects': './dev/.files/bin/update.mjs projects {{@}}',

	'wrangler': 'CLOUDFLARE_API_TOKEN="${USER_CLOUDFLARE_TOKEN:-}" npx wrangler {{@}}',

	...events, // e.g., `on::madrun:default:new`.
};
